version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: apt-get update && apt-get install -y --allow-unauthenticated libc6-dev libgdiplus libx11-dev && rm -rf /var/lib/apt/lists/*
      - run: dotnet build ./src/ -c Debug
#      - run: dotnet test ./src/ -c Debug --no-build
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build ./src/ -c Release -p:Version=${CIRCLE_TAG}
#      - run: dotnet test ./src/ -c Release --no-build
      - run: dotnet pack ./src/TableIO/TableIO.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./src/TableIO.ClosedXml/TableIO.ClosedXml.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./src/TableIO.NPOI/TableIO.NPOI.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/TableIO/bin/Release
          destination: ./TableIO/
      - store_artifacts:
          path: ./src/TableIO.ClosedXml/bin/Release
          destination: ./TableIO.ClosedXml/
      - store_artifacts:
          path: ./src/TableIO.NPOI/bin/Release
          destination: ./TableIO.NPOI/
      - run: dotnet nuget push ./src/TableIO/bin/Release/TableIO.${CIRCLE_TAG}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_KEY}
      - run: dotnet nuget push ./src/TableIO.ClosedXml/bin/Release/TableIO.ClosedXml.${CIRCLE_TAG}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_KEY}
      - run: dotnet nuget push ./src/TableIO.NPOI/bin/Release/TableIO.NPOI.${CIRCLE_TAG}.nupkg -s https://api.nuget.org/v3/index.json -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/
